load("py", "py_source_library")

py_source_library(
    name = "sourcelibrary",
    package_name = "sourcelibrary",
    sources = file(
        "setup.py",
        "src/sourcelibrary/__init__.py",
        "src/sourcelibrary/greet.py",
    ),
    dependencies = [],
)