load("lib://py", "py_source_library")

sourcelibrary = py_source_library(
    name = "sourcelibrary",
    package_name = "sourcelibrary",
    sources = glob(
        "setup.py",
        "src/sourcelibrary/__init__.py",
        "src/sourcelibrary/greet.py",
    ),
    dependencies = [],
)