load("py", "py_pypi_library")

pytest = py_pypi_library(
    name = "pytest",
    dependencies = [
        py_pypi_library(name = "packaging"),
        py_pypi_library(name = "attrs"),
        py_pypi_library(name = "more-itertools"),
        py_pypi_library(name = "atomicwrites"),
        py_pypi_library(name = "pluggy"),
        py_pypi_library(name = "py"),
        py_pypi_library(name = "importlib-metadata"),
        py_pypi_library(name = "wcwidth"),
        py_pypi_library(name = "pyparsing"),
        py_pypi_library(name = "six"),
        py_pypi_library(name = "zipp"),
    ],
)